CAMEL-5248: Running camel:run with blueprint gets a java.lang.NoClassDefFoundError: org.osgi.vendor.framework property not set
git-svn-id: https://svn.apache.org/repos/asf/camel/trunk@1334367 13f79535-47bb-0310-9956-ffa450edef68

Conflicts:

	tooling/maven/camel-maven-plugin/src/main/java/org/apache/camel/maven/RunMojo.java